apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cicd-demo-
spec:
  volumes:
    - name: docker-credentials
      secret:
        secretName: docker-credentials
    - name: github-token
      secret:
        secretName: github-token
  entrypoint: cicd-demo
  templates:
    - name: cicd-demo
      steps:
        - - name: checkout
            template: checkout
        - - name: build
            template: build
            arguments:
              parameters:
                - name: tag
                  value: "{{steps.checkout.outputs.parameters.tag}}"
        - - name: update
            template: update
            arguments:
              parameters:
                - name: tag
                  value: "{{steps.checkout.outputs.parameters.tag}}"

    - name: checkout
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["apk add git &&
          git clone https://github.com/sheffnercarlisle/cicd-app.git &&
          cd cicd-app &&
          git rev-parse --short HEAD > /tmp/tag"]
      outputs:
        parameters:
          - name: tag
            valueFrom:
              path: /tmp/tag

    - name: build
      inputs:
        parameters:
          - name: tag
      container:
        image: gcr.io/kaniko-project/executor:latest
        args: ["--context=git://github.com/sheffnercarlisle/cicd-app.git",
               "--destination=cpsma/cicd-app:{{inputs.parameters.tag}}"]
        volumeMounts:
          - name: docker-credentials
            mountPath: /kaniko/.docker/config.json
            subPath: config.json

    - name: update
      inputs:
        parameters:
          - name: tag
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["apk add git &&
          git clone https://github.com/sheffnercarlisle/cicd-deployment.git &&
          cd cicd-deployment &&
          git config --global user.email 'argo@carlisle.k12.ma.us' &&
          git config --global user.name 'Argo Workflow' &&
          sed -i 's|\\(cpsma/cicd-app:\\).*|\\1{{inputs.parameters.tag}}|g' deployment.yml &&
          git add . &&
          git commit -m 'Update image to {{inputs.parameters.tag}}' &&
          git push https://argo:$TOKEN@github.com/sheffnercarlisle/cicd-deployment.git"]
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
